language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - "mkdir -p ~/.npm"
install:
  - sudo apt-get install --force-yes libbluetooth-dev
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=46eeae8b45dbc4aaea2f86c158b984b3d4bfddd1bf323e6b8c9cd4c8bc53d216 codeclimate-test-reporter < coverage/lcov.info
